---
# tasks file for thredds
# Ubuntu
##############################################################################
# - name: Update apt cache and make sure Java is installed
#   apt:
#     name: openjdk-11-jdk
#     update_cache: yes
#     state: present
##############################################################################
# RHEL
##############################################################################
- name: Update yum cache and make sure Java is installed
  yum:
    name:
      - java-11-openjdk-devel
    update_cache: yes
    state: present

- name: Add the tomcat user
  user:
    name: tomcat
    shell: /bin/false
    home: /opt/tomcat

- name: Check for Tomcat server
  stat:
    path: "/tmp/{{ tomcat_tar }}"
  register: tomcat_stat_result

- name: Download Tomcat server
  get_url:
    url: "{{ tomcat_url }}"
    dest: /tmp
  when: not tomcat_stat_result.stat.exists

- name: Extract Tomcat server
  command: tar -xf "/tmp/{{ tomcat_tar }}" -C /tmp
  when: not tomcat_stat_result.stat.exists

- name: Move Tomcat server
  command: mv "/tmp/{{ tomcat_untar }}" /opt/tomcat
  ignore_errors: true
  when: not tomcat_stat_result.stat.exists

- name: Create link to latest Tomcat
  file:
    src: "/opt/tomcat/{{ tomcat_untar }}"
    dest: /opt/tomcat/latest
    owner: tomcat
    group: tomcat
    state: link

- name: Chown Tomcat server
  file:
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    recurse: yes
    state: directory

- name: Create Tomcat server service
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  notify: Restart Tomcat

- name: Create content root directory if it does not exist
  file:
    path: "{{ content_root }}"
    state: directory
    owner: tomcat
    group: tomcat
    mode: '0755'

- name: Check for THREDDS server war
  stat:
    path: /opt/tomcat/latest/webapps/thredds.war
  register: thredds_stat_result

- name: Download THREDDS server
  get_url:
    url: "{{ thredds_url }}"
    dest: /tmp/thredds.war
  when: not thredds_stat_result.stat.exists

- name: Deploy THREDDS war to Tomcat
  command: mv /tmp/thredds.war /opt/tomcat/latest/webapps
  when: not thredds_stat_result.stat.exists

- name: Wait until THREDDS config is present before continuing
  wait_for:
    path: "{{ content_root }}/thredds/threddsConfig.xml"